mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver